export const GET_USER = "GET_USER";
export const ADD_USER = "ADD_USER";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const RESET_USER = "RESET_USER";
export const CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT";
export const UPDATE_CANCEL_APPOINTMENT_ERROR = "UPDATE_CANCEL_APPOINTMENT_ERROR";
export const BOOK_APPOINTMENT = 'BOOK_APPOINTMENT';