//RESET USER
export const RESET_USER = "RESET_USER";
//LOGIN USER
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const RESET_LOGIN_ERROR = 'RESET_LOGIN_ERROR';
//CREATE STUDENT
export const CREATE_STUDENT = "CREATE_STUDENT";
export const CREATE_STUDENT_ERROR = 'CREATE_STUDENT_ERROR';
export const RESET_CREATE_STUDENT_ERROR = 'RESET_CREATE_STUDENT_ERROR';
//CREATE TUTOR
export const CREATE_TUTOR = "CREATE_TUTOR";
export const CREATE_TUTOR_ERROR = 'CREATE_TUTOR_ERROR';
export const RESET_CREATE_TUTOR_ERROR = 'RESET_CREATE_TUTOR_ERROR';
//BOOK APPOINTMENT
export const BOOK_APPOINTMENT = 'BOOK_APPOINTMENT';
export const BOOK_APPOINTMENT_ERROR = 'BOOK_APPOINTMENT_ERROR';
export const RESET_BOOK_APPOINTMENT_ERROR = 'RESET_BOOK_APPOINTMENT_ERROR';
//CREATE APPOINTMENT
export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const CREATE_APPOINTMENT_ERROR = 'CREATE_APPOINTMENT_ERROR';
export const RESET_CREATE_APPOINTMENT_ERROR = 'RESET_CREATE_APPOINTMENT_ERROR'
//CANCEL APPOINTMENT
export const CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT";
export const CANCEL_APPOINTMENT_ERROR = "CANCEL_APPOINTMENT_ERROR";
export const RESET_CANCEL_APPOINTMENT_ERROR = "RESET_CANCEL_APPOINTMENT_ERROR";
//GET TUTORS
export const GET_TUTORS = 'GET_TUTORS';
export const GET_TUTORS_ERROR = 'GET_TUTORS_ERROR';
export const RESET_GET_TUTORS_ERROR = 'RESET_GET_TUTORS_ERROR';

